version: '3.8'

services:
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    container_name: briw_solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    networks:
      - briw_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system" ]
      interval: 30s
      timeout: 10s
      retries: 5

  tika:
    image: apache/tika:latest
    container_name: briw_tika
    ports:
      - "9998:9998"
    networks:
      - briw_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: briw_backend
    ports:
      - "5001:3000"
    volumes:
      - backend_uploads:/app/uploads
    environment:
      - PORT=3000
      - SOLR_URL=http://solr:8983/solr/search_core
    depends_on:
      solr:
        condition: service_healthy
    networks:
      - briw_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: briw_frontend
    ports:
      - "5173:5173"
    networks:
      - briw_net
    depends_on:
      - backend

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: briw_crawler
    ports:
      - "5000:5000"
    environment:
      - SOLR_URL=http://solr:8983/solr/search_core
      - TIKA_URL=http://tika:9998
      - API_URL=http://backend:3000/api
    depends_on:
      solr:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - briw_net

  postgres:
    image: postgres:15-alpine
    container_name: briw_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: briw_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - briw_net

volumes:
  solr_data:
  backend_uploads:
  postgres_data:


networks:
  briw_net:
    driver: bridge
